version: "3.9"

networks:
  minimizing_network:
    driver: bridge

services:
  minimizing-mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - minimizing_network

  minimizing-api:
    image: minimizing-api
    command: ["/wait-for-it.sh", "-t", "30", "minimizing-mysql:3306", "--", "java", "-jar", "minimizing-api.jar"]
    environment:
      DB_HOST: minimizing-mysql
    ports:
      - "8080:8080"
    networks:
      - minimizing_network
    depends_on:
      - minimizing-mysql