server:
  port: 8080

    #servlet:
  #context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    locations: db/migration, db/datatest

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #format_sql: true
    show-sql: true
      #generate-ddl: true
      #hibernate:
    #ddl-auto: create-drop

  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
    #max-file-size: 20KB
  freemarker:
    settings:
      locale: pt_BR

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks
        opaquetoken:
          introspection-uri: http://localhost:8080/oauth2/introspect
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}

springdoc:
  packages-to-scan: com.dcconnect.minimizingwaste.api
  paths-to-match: /v1/**
  oAuthFlow:
    authorizationUrl: http://localhost:8080/oauth2/authorize
    tokenUrl: http://localhost:8080/oauth2/token

  swagger-ui:
    oauth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
---
minimizing-waste:
  storage:
    local:
      directory: /home/silvio/avatar

    s3:
      access-key-id: ${ACCESS_KEY_ID}
      secret-access-key: ${SECRET_ACCESS_KEY}
      bucket: minimizing-waste
      region: us-east-1
      directory: user-photo

    #Enable photo storage services type, for example:
    # - "s3" to PhotoStorageService.class or  "local" to LocalPhotoStorage.class
    type: s3

  auth:
    provider-url: http://localhost:8080
  jwt:
    keystore:
      password: ${STORE_PASSWORD}
      keypair-alias: minimizingwaste
      jks-location: ${JKS_LOCATION}

  security:
    redirect:
      client: http://127.0.0.1:5173