server:
  port: 8080

  #servlet:
    #context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost/minimizing_waste?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: mysql123

  flyway:
    locations: db/migration, db/datatest

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #format_sql: true
    show-sql: true
    #generate-ddl: true
    #hibernate:
      #ddl-auto: create-drop

  jackson:
    deserialization:
      fail-on-ignored-properties: true
      fail-on-unknown-properties: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      #max-file-size: 20KB
  freemarker:
    settings:
      locale: pt_BR

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks
        opaquetoken:
          introspection-uri: http://localhost:8080/oauth2/introspect
          client-id: minimizing-web
          client-secret: 123

springdoc:
  packages-to-scan: com.dcconnect.minimizingwaste.api
  paths-to-match: /v1/**
  oAuthFlow:
    authorizationUrl: http://localhost:8080/oauth2/authorize
    tokenUrl: http://localhost:8080/oauth2/token

  swagger-ui:
    oauth:
      client-id: minimizing-web
      client-secret: web123
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
---
minimizing-waste:
  storage:
    local:
      directory: /avatar
    s3:
      #access-key-id:
      #secret-access-key:
      bucket: minimizing-waste
      region: us-east-1
      directory: user-photo

    #Enable photo storage services type, for example:
    # - "s3" to PhotoStorageService.class or  "local" to LocalPhotoStorage
    type: s3

  auth:
    provider-url: http://localhost:8080
  jwt:
    keystore:
      password: 356278
      keypair-alias: minimizingwaste
      jks-location: base64:MIILRgIBAzCCCvAGCSqGSIb3DQEHAaCCCuEEggrdMIIK2TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFOUi/me5RjT9R0rM4ukQW71yfTP1AgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQAYVutgv0v8KeQYgNKsQpPwSCBNDpEpXVmuhluTQmmQbkTZwRq1fiWs+sgXwsIlkIGgq4M19IwaBKR9WFL0I2J9yewpHvznpUrpjnM9UZC63/4ayK4452uiDyVRMllTqC8Wyd2C2tPhz+PEvMgaGcBXXAtcm2cHYanCA/eIax59RJOK7Cl7DQBSb/UJeEhocJjCbH31HlnUu5HJ287aynZvbsfRHevY3TrcCSz0rUSriD1VdJ03+qnpT9VWazPXOJWCBDi3J48adRJVZM+0onvaM1Z7fGIs4cZBJZSL0aPettgXD60XatrofETZu4CZlmiRt228WsaLZq4brmfQwF8UeKxcdGFhjYhVUxpMRh36TAtwpaqPNkj3tQ5Cmkhrh/AHNAqzt7HwffrcIaRj2R4azGfpFeD5yQzY6syuJTGOpBBMT/ZDiLBdi6y6OG3KJMtf7DG8XOshsa2K68bN61hbZymOjttF7HsrrwFEo7A4+ZP9x3S7Rp5bHlvLKTR/gOwmfcUsoD2ewOFJ2xiCXZTYwDPPbzFJfwyyO/aYeyXaVAGvy3iBi1zFZqUPHD5EeVyA2CsAN0APBdTFbfSVVRS1b9TdXkD30fQbecHUnLeMwyTUaEqIar6bIxI4qA6z5vfOLRFX2lqWXo0JkbOCeZ54EbBqvnEuqu6+7/188k/UO9Ne1bLOkfyxmjqS3sRrKGYhlCmxjwtAtOHIgpv1HNSHqzYZEz+sdC3RTTS+ShJ6/uFyp4gfq/cL7aEnd6fzcPEaCqJ2IGluVb3w1VDu8MtN0u5SCePD0hvxD2RZIpQOLtzPinajsGLzJtXmM0ZzCJPnaLwRAAckxKsvAFV/1/deH+PZqBvYfy9keCy09Stu88/HPFiiDORD0asWCvH2wiRTj3tQEz/WM0bnBLek086b/skG8bqRFDPHVmYXA4vOjQ9mu72s3ygjiOpGfMN2AtiG/sLXPDhXWADkRJw3DCcJf1XXv1z38sRBuSZ+g9qUoAZdnA+gn2gFSS+bTs491VpYRq5Jn7G2MY9q5wKH0ZsYRrnkLedtvEsqOhkVN6BMr+DaSjR/+4VE9US9ngGZ88mwszR6vQ12VU8CL7BM2ypv5ds9XJ6/J/uQGcOK2ipNVM0VD5xIGOjI3fTf6qN591yM+4UJN4535Er3gDEWHMa6E2937ftR7rrEEnkDPgmcnpFePvKwzvQOqAWIWk5xmLDaeXSgdt7iEJMTDD+fl1WR2RM/B9cjH+7k5TN6NyvSU3TDlwyiElbaDUGrIiuYZNy839ZcEQa00337dvicLyzjeWDSb95CQNn+K6Z1wthzs8TuAAHg9a3efbFP6PsuPDwr9ms9YQ986uZcpxCV0kGCUzKzm4Yx/3VhssIXhpCdUd7qPjITNKqLIjQ1FflMU8OR+GJYu0sSxO1zrsxzCc8481nfLhXO6blLX9SnUiRbIgP3P3Fibo37OyAhV7sSQpAHcSRxC9U0jWrVtLJCbWEhJvjwqqbQx5h9hC0j8bd6vXzE2odhafsgtGKWPuszBoDt6/4PK8ehG0myC50mdyoAjXgsMzaeNJScg1S3M2OvJS3SxjPchQXjfUJggTRcrE1KnG+x9aqCohR7KHkblCvT2ZxfKL4Vxc+pGgDKkIkbQzjDvS+4MQwxiAKABTwdKrPQyi2TFSMC0GCSqGSIb3DQEJFDEgHh4AbQBpAG4AaQBtAGkAegBpAG4AZwB3AGEAcwB0AGUwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTY3NTE4NzExNDA0NzCCBREGCSqGSIb3DQEHBqCCBQIwggT+AgEAMIIE9wYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBQ7opAhzKdqwXo7Y+hOalg6uicwTAICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEP0Y6qXHi1oJrmyUSuIsNweAggSA+GDYM0x31LC+tzGrYxb26BUW03KMoswIZnbG3AbLe1hcpsNnlmGe4KS6/W2SWVDCxdwk9jkb0TW2vlsl4nEnG7d4hqEPN11+pQrqI83YW89D9R6irJQx+V+nMo190Off/WmSi4/Uc20/X5QlpFKGae1Q69ojSowmfZ2P1+EjOtJEiiPp4Op9MmcnUn40TxyeeQUNFfadPTQI/PEd/lmruiMfgcRZIM2X9OLww6T6ryE7wPErlMyiCXM8YZIrpRigy4IBiuBbGYLothZGd8UZb7aufpVSLw5EwL9aE51NAeQzb/rkPSIrxEGJlqDVpbRIIQlXFjmkb0CN0O6nPVnJdu6rWo275efNLC+Hx+c6f98FVS6r+DuqvCt5i9f8ZqZS9r2AiO1todOEbgeerVT24+rhV2g9nF6gSSvPzR8LP84MjuRe/P1f8Jnh5+3Rpm7nMsCfZ3sbVsh+hueLnUqT4h0D9dMjFSiMo03EZ4Op1rpmNYGk7tM11DOYjbK96zOtuYDPcF8C5MTkbrpU97mzuA/5UQbRHZdRv50E+48CYrIJmg09gy2gziIKLiu3P0JUjr6V4Jin4WFtuB++EkXRN0NzpmlDcPkc8eMxJQW0gQxhpEdXaHJ9nf3wpb7tKggic90cWP1eV9XEuVd0Y5tdyQUmDFmXgH43HvfHnTvSDWdL7FG6mWTExlWDZrvHWT93Xb3q/jVIyEzYZxOLjpPoCFVMEppcnwlJd+hTZq+YDKhgc3jR4DKKzUaLIke6cR7SLCNaXfx4ff9Mv2hg2iRBtAkrIqZtBLYK2DQSWAdgJXKL2uyCL9oKWH+El+kbeSucimF1RcQzlF5ufFGoqaQrXajVnDi8IwG68TgjGGyIS7ZPcSwW6kxvhkqonPEFulnlt8CUhx7daDdIeJ3/DvSmkCA1BzATco+8Zx/f383raxFc0f6cVMbICe61tiJC2lWbBeLhLuVIuhfgTB14BV9HYSdJX4yUOqy9OEAg0PSt81AnriILTGU7RLAJWIQ4SZaa3tHOiCN5BoopLc9eI5a53tALWMVyqZDiA4HjfpDCDzTKWh5P6vcGFdMgzG3fXPg7/48pSa5DjfxQ4abo8koTA0yRO6Z/ZwE+WUIYDPrgDYvHHj6C5LsQOSeD0IZNH+n0cjNWqzm+VhQ0caLvW3y8SPXNEFX6F6nkiVUTF9m849ZED68udipSW+a1trdA3YjN2K8jyHYg1Qt4dimcJzB34lEKAjLX+C0S7wjs+OotP7KJ3ss6XW+UHlfjY0EHLwFlVshPDutGuHjXCY9/5JBDVj69P/BuFdlusFHooQwIwSTMYA/5hcrPi3Qa4s9kDZP3jSIxVDD44XUAhc29LOyUr6ztzJEC1tYO2BrKmoOyhvNIV/uXNDH5mN6m71ubybRSD6caaeb2KthpmRNJ9CEjGqErUposxRx5JoKxgPLc6I2T2UFYgo5fsKntyCFnxB1x+d5LMq6vBjdKVAYLUjgddsBtwe9NDqudmzVduZtdfRoSOei6hsuAfYdOKkg2/341ME0wMTANBglghkgBZQMEAgEFAAQgESYxoFNvHnOXrQnbN4H/ZW94kJ8kI8yVcGGUWBUwjxIEFDUmCvj6G0TQETMDzptgqR7Ym6TvAgInEA==

  security:
    redirect:
      client: http://127.0.0.1:5173