/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/work-stations/{workStationId}": {
    /** Deleta uma estação de trabalho */
    get: operations["findOrFail"];
    /** Edita uma estação de trabalho */
    put: operations["update"];
    /** Deleta uma estação de trabalho */
    delete: operations["delete"];
  };
  "/v1/users/{userId}": {
    /** Busca um usuário pelo ID */
    get: operations["findOrFail_1"];
    /** Edita um usuário */
    put: operations["update_1"];
    /** Deleta um usuário */
    delete: operations["delete_1"];
  };
  "/v1/users/{userId}/password": {
    /** Altera a Senha do usuário */
    put: operations["changePassword"];
  };
  "/v1/users/{userId}/access-groups/{accessGroupId}": {
    /** Associa um determinado grupo ao usuário atual */
    put: operations["associate"];
    /** Disassocia um determinado grupo ao usuário atual */
    delete: operations["disassociate"];
  };
  "/v1/supplies/materials/{supplyId}": {
    /** Edita um recurso do tipo material */
    put: operations["updateMaterial"];
  };
  "/v1/supplies/equipments/{supplyId}": {
    /** Edita um recurso do tipo equipamento */
    put: operations["updateEquipment"];
  };
  "/v1/supplies-movements/{supplyMovementId}": {
    /** Deleta um movimento de recurso */
    get: operations["findById_1"];
    /** Edita um movimento de recurso */
    put: operations["update_2"];
    /** Deleta um movimento de recurso */
    delete: operations["delete_3"];
  };
  "/v1/supplies-movements/give-back/{supplyMovementId}": {
    /** Devolve uma quantia de recurso */
    put: operations["giveBackSupply"];
  };
  "/v1/sectors/{sectorId}": {
    /** Busca um setor pelo ID */
    get: operations["findOrFail_2"];
    /** Edita um setor */
    put: operations["update_3"];
    /** Deleta um setor */
    delete: operations["delete_4"];
  };
  "/v1/assignments/{assignmentId}": {
    /** Busca uma taerfa pelo ID */
    get: operations["findOrFail_3"];
    /** Edita uma tarefa */
    put: operations["update_4"];
    /** Deleta uma tarefa */
    delete: operations["delete_5"];
  };
  "/v1/assignments/{assignmentId}/employee-responsible/{employeeResponsibleId}/disassociate": {
    /** Disassocia um colaborador a determinada tarefa */
    put: operations["detachEmployee"];
  };
  "/v1/assignments/{assignmentId}/employee-responsible/{employeeResponsibleId}/associate": {
    /** Associa um colaborador a determinada tarefa */
    put: operations["attachEmployee"];
  };
  "/v1/assignments/{assignmentId}/conclusion": {
    /** Conclui ou não uma tarefa */
    put: operations["completeAssignment"];
  };
  "/v1/assignments/{assignmentId}/approval": {
    /** Aprova ou reprova uma tarefa */
    put: operations["approveAssignment"];
  };
  "/v1/access-groups/{accessGroupId}": {
    /** Edita um grupo de acesso */
    put: operations["update_5"];
    /** Deleta um grupo de acesso */
    delete: operations["delete_6"];
  };
  "/v1/access-groups/{accessGroupId}/permissions/{permissionId}": {
    /** Associa as permissões relacionadas ao grupo atual */
    put: operations["associate_1"];
    /** Disassocia as permissões relacionadas ao grupo atual */
    delete: operations["disassociate_1"];
  };
  "/v1/work-stations": {
    /** Lista as estações de trabalho */
    get: operations["search"];
    /** Cria uma nova estação de trabalho */
    post: operations["create"];
  };
  "/v1/users": {
    /** Lista os usuários */
    get: operations["search_1"];
    /** Cria um novo usuário */
    post: operations["create_1"];
  };
  "/v1/users/upload/avatar": {
    /** Cria um avatar de usuário */
    post: operations["upload"];
  };
  "/v1/supplies/materials": {
    /** Cria um novo recurso do tipo material */
    post: operations["createMaterial"];
  };
  "/v1/supplies/equipments": {
    /** Cria um novo recurso do tipo equipamento */
    post: operations["createEquipment"];
  };
  "/v1/supplies-movements": {
    /** Lista os movimentos de recursos */
    get: operations["all_1"];
    /** Cria um novo movimento de recurso */
    post: operations["create_2"];
  };
  "/v1/sectors": {
    /** Lista os setores */
    get: operations["search_3"];
    /** Cria um novo setor */
    post: operations["create_3"];
  };
  "/v1/assignments": {
    /** Lista as Tarefas */
    get: operations["search_5"];
    /** Cria uma nova tarefa */
    post: operations["create_4"];
  };
  "/v1/access-groups": {
    /** Lista os grupos de acesso */
    get: operations["all_4"];
    /** Cria um grupo de acesso */
    post: operations["create_5"];
  };
  "/v1/users/{userId}/access-groups": {
    /** Lista os grupos de acesso  de cada usuário */
    get: operations["all"];
  };
  "/v1/users/{assignmentId}/assignments": {
    /** Lista os usuários atribuídos ou não a tarefa atual */
    get: operations["allAssigned"];
  };
  "/v1/supplies": {
    /** Lista recursos */
    get: operations["search_2"];
  };
  "/v1/supplies/{supplyId}": {
    /** Busca um recurso por ID */
    get: operations["findById"];
    /** Deleta um recurso */
    delete: operations["delete_2"];
  };
  "/v1/supplies-movement/notifications/available": {
    /** Lista as notificações enviadas, por recursos atribuídos */
    get: operations["findNotificationBySuppliesAvailable"];
  };
  "/v1/permissions": {
    /** Lista as permissões de cada grupo de acesso */
    get: operations["all_2"];
  };
  "/v1/notifications/assignments": {
    /** Lista as notificações enviadas por tarefas atribuídas ou não atribuídas */
    get: operations["findAllAssignedOrUnassigned"];
  };
  "/v1/notifications/assignments/available": {
    /** Lista as notificações enviadas, completas, aprovadas e por data */
    get: operations["search_4"];
  };
  "/v1/assignments/{assignmentId}/employee-responsible": {
    /** Lista colaboradores atribuídos a respectivas tarefas */
    get: operations["all_3"];
  };
  "/v1/access-groups/{accessGroupId}/permissions": {
    /** Lista as permissões relacionadas ao grupo atual */
    get: operations["all_5"];
  };
  "/v1/supplies-movements/vacancies/{supplyMovementId}": {
    /** Disponibiliza um movimento de recurso em estado ocioso */
    delete: operations["vacateSupply"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProblemObject: {
      /** @example title */
      name?: string;
      /** @example O campo título é obrigatório */
      userMessage?: string;
    };
    Problem: {
      /**
       * Format: int32
       * @example 400
       */
      status?: number;
      /** @example https://enfatiza7.com/invalidated-data */
      type?: string;
      /** @example Dados inválidos */
      title?: string;
      /** @example Um ou mais campos estão inválidos. Faça o preenchimento correto e tente novamente. */
      detail?: string;
      /** @example Um ou mais campos estão inválidos. Faça o preenchimento correto e tente novamente. */
      userMessage?: string;
      /**
       * Format: date-time
       * @example 2022-07-15T11:21:50.902245498Z
       */
      timestamp?: string;
      /** @description Lista de objetos ou campos que geraram o erro */
      objects?: components["schemas"]["ProblemObject"][];
    };
    SectorIdInput: {
      /**
       * Format: int64
       * @example 1
       */
      id: number;
    };
    WorkStationInput: {
      /** @example Bloco B Apto 27 */
      name: string;
      /** @example Próximo ao Jardim da Fachada */
      localization: string;
      sector: components["schemas"]["SectorIdInput"];
    };
    Links: {
      [key: string]: components["schemas"]["Link"];
    };
    SectorModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Acabamento */
      name?: string;
      _links?: components["schemas"]["Links"];
    };
    WorkStationModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Bloco B Apto 27 */
      name?: string;
      /** @example Próximo ao Jardim da Fachada */
      localization?: string;
      sector?: components["schemas"]["SectorModel"];
      _links?: components["schemas"]["Links"];
    };
    UserUpdateInput: {
      /** @example Pedro Oliveira Bassi */
      name: string;
      /** @example 99999999999 */
      cpf: string;
      /** @example pedro@gmail.com */
      email: string;
      /** @example 17996079654 */
      whatsApp: string;
      /** @example Azulejista */
      office: string;
      /** @example Instalador de Revestimento */
      occupation: string;
      /** @example Curso Superior Incompleto */
      literate: string;
      /** @example https://localhost:8080/directory/92352jfç2efk05iy45yrlkfmsdgjlkdrf_file */
      avatarUrl?: string;
    };
    AccessGroupSummaryModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Engenheiro */
      name?: string;
      _links?: components["schemas"]["Links"];
    };
    UserDetailedModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Pedro Oliveira Bassi */
      name?: string;
      /** @example 99999999999 */
      cpf?: string;
      /** @example pedro@gmail.com */
      email?: string;
      /** @example 17996079654 */
      whatsApp?: string;
      /** @example Azulejista */
      office?: string;
      /** @example Instalador de Revestimento */
      occupation?: string;
      /** @example Curso Superior Incompleto */
      literate?: string;
      /** @example https://localhost:8080/directory/dgfodsg809427yt3ijbvfdlkh0i650k50_file */
      avatarUrl?: string;
      /**
       * Format: date-time
       * @example 2023-01-03T22:08:00Z
       */
      createdAt?: string;
      accessGroups?: components["schemas"]["AccessGroupSummaryModel"][];
      _links?: components["schemas"]["Links"];
    };
    PasswordInput: {
      /** @example 12k43jd8#* */
      currentPassword: string;
      /** @example 1938kdk# */
      newPassword: string;
    };
    SupplyDescriptionInput: {
      /** @example Caixa de Papel */
      packing: string;
      /**
       * Format: int64
       * @example 1
       */
      quantity: number;
      /** @example 50 */
      measure?: number;
      /**
       * @example KG
       * @enum {string}
       */
      measureUnitType: "UNIDADE" | "ML" | "LITRO" | "M2" | "M3" | "KG" | "TONELADA";
    };
    SupplyMaterialInput: {
      /** @example Recurso */
      name: string;
      supplyDescription: components["schemas"]["SupplyDescriptionInput"];
      supplyType: string;
      manipulation: string;
    };
    SupplyDescriptionDetailedModel: {
      /** @example Saco plástico */
      packing?: string;
      /**
       * Format: int64
       * @example 3
       */
      quantity?: number;
      /** @example 40 */
      measure?: number;
      /** @example 120 */
      total?: number;
      /**
       * @example KG
       * @enum {string}
       */
      measureUnitType?: "UNIDADE" | "ML" | "LITRO" | "M2" | "M3" | "KG" | "TONELADA";
    };
    SupplyDetailedModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Cimento */
      name?: string;
      /**
       * @example EQUIPAMENTO
       * @enum {string}
       */
      supplyType?: "MATERIAL" | "EQUIPAMENTO";
      /**
       * @example PEQUENO
       * @enum {string}
       */
      bulk?: "PEQUENO" | "MÉDIO" | "GRANDE";
      /**
       * @example TRANSMUTÁVEL
       * @enum {string}
       */
      manipulation?: "TRANSMUTÁVEL" | "IMUTÁVEL";
      supplyDescription?: components["schemas"]["SupplyDescriptionDetailedModel"];
      _links?: components["schemas"]["Links"];
    };
    SupplyEquipmentInput: {
      /** @example Recurso */
      name: string;
      supplyDescription: components["schemas"]["SupplyDescriptionInput"];
      supplyType: string;
      bulk: string;
    };
    NotificationInput: {
      /** @example Início de Instalação de Revestimentos */
      title: string;
      /** @example Liberação de Banheiros */
      reason: string;
      /** @example Instalação de gessos nos tetos */
      goal: string;
    };
    SupplyIdInput: {
      /**
       * Format: int64
       * @example 1
       */
      id: number;
    };
    SupplyMovementInput: {
      /** @example true */
      movable: boolean;
      /**
       * Format: int64
       * @example 3
       */
      reservedQuantity: number;
      notification: components["schemas"]["NotificationInput"];
      workStation: components["schemas"]["WorkStationIdInput"];
      supply: components["schemas"]["SupplyIdInput"];
      employeeResponsible: components["schemas"]["UserIdInput"];
    };
    UserIdInput: {
      /**
       * Format: int64
       * @example 2
       */
      id: number;
    };
    WorkStationIdInput: {
      /**
       * Format: int64
       * @example 1
       */
      id: number;
    };
    NotificationModel: {
      /**
       * Format: date-time
       * @example 2023-01-07T22:50:00Z
       */
      createdAt?: string;
      /** @example Início de Instalação de Revestimentos */
      title?: string;
      /** @example Liberação de Banheiros */
      reason?: string;
      /** @example Instalação de gessos nos tetos */
      goal?: string;
    };
    SupplyMovementModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example true */
      notBusy?: boolean;
      /** @example false */
      movable?: boolean;
      /**
       * Format: int64
       * @example 20
       */
      allocatedQuantity?: number;
      notification?: components["schemas"]["NotificationModel"];
      workStation?: components["schemas"]["WorkStationModel"];
      supply?: components["schemas"]["SupplySummaryModel"];
      _links?: components["schemas"]["Links"];
    };
    /** @example 1 */
    SupplySummaryModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Recurso */
      name?: string;
      supplyDescription?: components["schemas"]["SupplyDescriptionDetailedModel"];
      _links?: components["schemas"]["Links"];
    };
    DevolvedSupplyMovementInput: {
      /**
       * Format: int64
       * @example 2
       */
      reservedQuantity: number;
    };
    SectorInput: {
      name: string;
    };
    AssignmentInput: {
      /** @example Revestimento dos Banheiros */
      title: string;
      /**
       * Format: date-time
       * @example 2022-12-28T13:00:33Z
       */
      startDate: string;
      /**
       * Format: date-time
       * @example 2023-01-20T13:00:33Z
       */
      deadline: string;
      /** @example OBRAS */
      nature: string;
      workStation: components["schemas"]["WorkStationIdInput"];
      notification: components["schemas"]["NotificationInput"];
    };
    AssignmentModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Revestimento dos Banheiros */
      title?: string;
      /**
       * Format: date-time
       * @example 2022-12-28T13:00:33Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @example 2023-01-20T13:00:33Z
       */
      deadline?: string;
      /**
       * Format: date-time
       * @example 2023-01-20T13:00:33Z
       */
      endDate?: string;
      /** @example true */
      completed?: boolean;
      /** @example false */
      approved?: boolean;
      /**
       * @example OBRAS
       * @enum {string}
       */
      nature?: "LIMPEZA" | "OBRAS";
      workStation?: components["schemas"]["WorkStationModel"];
      employeesResponsible?: components["schemas"]["UserAssignedModel"][];
      _links?: components["schemas"]["Links"];
    };
    UserAssignedModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Pedro Oliveira Bassi */
      name?: string;
      /** @example 17996079654 */
      whatsApp?: string;
      /** @example Azulejista */
      office?: string;
      /** @example Instalador de Revestimento */
      occupation?: string;
      /** @example https://localhost:8080/directory/lkdsfsdjlg439t74309jg3gikogiewrig_file */
      avatarUrl?: string;
      _links?: components["schemas"]["Links"];
    };
    AssignmentNotificationInput: {
      notification: components["schemas"]["NotificationInput"];
    };
    /** @description Representação da Conclusão da Tarefa */
    AssignmentCompletedInput: {
      /** @example true */
      completed: boolean;
    };
    /** @description Representação da Aprovação da Tarefa */
    AssignmentApprovedInput: {
      /** @example true */
      approved: boolean;
      /**
       * Format: date-time
       * @example 2023-01-20T13:00:33Z
       */
      endDate?: string;
    };
    AccessGroupInput: {
      /** @example Engenheiro */
      name: string;
    };
    UserInput: {
      /** @example Pedro Oliveira Bassi */
      name: string;
      /** @example 9585hf7#_ */
      password: string;
      /** @example 99999999999 */
      cpf: string;
      /** @example pedro@gmail.com */
      email: string;
      /** @example 17996079654 */
      whatsApp: string;
      /** @example Azulejista */
      office: string;
      /** @example Instalador de Revestimento */
      occupation: string;
      /** @example Curso Superior Incompleto */
      literate: string;
      /** @example https://localhost:8080/directory/92352jfç2efk05iy45yrlkfmsdgjlkdrf_file */
      avatarUrl?: string;
    };
    AvatarInput: {
      /** Format: binary */
      file: string;
    };
    AvatarUrlModel: {
      /** @example https://localhost:8080/directory/901582309572090idjksflkdlsrow4t_file */
      avatarUrl?: string;
    };
    CollectionModelWorkStationModel: {
      _embedded?: {
        workStations?: components["schemas"]["WorkStationModel"][];
      };
      _links?: components["schemas"]["Links"];
    };
    PageMetadata: {
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int64 */
      totalPages?: number;
      /** Format: int64 */
      number?: number;
    };
    PagedModelUserDetailedModel: {
      _embedded?: {
        users?: components["schemas"]["UserDetailedModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    CollectionModelAccessGroupSummaryModel: {
      _embedded?: {
        accessGroups?: components["schemas"]["AccessGroupSummaryModel"][];
      };
      _links?: components["schemas"]["Links"];
    };
    PagedModelUserAssignedModel: {
      _embedded?: {
        users?: components["schemas"]["UserAssignedModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    PagedModelSupplySummaryModel: {
      _embedded?: {
        supplies?: components["schemas"]["SupplySummaryModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    PagedModelSupplyMovementModel: {
      _embedded?: {
        suppliesMovements?: components["schemas"]["SupplyMovementModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    PagedModelSupplyMovementNotificationModel: {
      _embedded?: {
        supplyMovementNotifications?: components["schemas"]["SupplyMovementNotificationModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    SupplyMovementNotificationModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      supply?: components["schemas"]["SupplySummaryModel"];
      workStation?: components["schemas"]["WorkStationDetailedModel"];
      notification?: components["schemas"]["NotificationModel"];
      _links?: components["schemas"]["Links"];
    };
    WorkStationDetailedModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Bloco G Apto 21 */
      name?: string;
      /** @example Bloco G Apto 21 */
      localization?: string;
      sector?: components["schemas"]["SectorModel"];
    };
    SectorFilter: {
      sectorName?: string;
    };
    CollectionModelSectorModel: {
      _embedded?: {
        sectors?: components["schemas"]["SectorModel"][];
      };
      _links?: components["schemas"]["Links"];
    };
    CollectionModelPermissionDetailedModel: {
      _embedded?: {
        permissions?: components["schemas"]["PermissionDetailedModel"][];
      };
      _links?: components["schemas"]["Links"];
    };
    PermissionDetailedModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example CONSULT_SUPPLIES */
      name?: string;
      /** @example Permite Consultar Recursos */
      description?: string;
      _links?: components["schemas"]["Links"];
    };
    AssignmentNotificationModel: {
      /** Format: int64 */
      id?: number;
      /** @example Início de Tarefa */
      title?: string;
      /** Format: date-time */
      deadline?: string;
      workStation?: components["schemas"]["WorkStationDetailedModel"];
      notification?: components["schemas"]["NotificationModel"];
      _links?: components["schemas"]["Links"];
    };
    PagedModelAssignmentNotificationModel: {
      _embedded?: {
        notificationsAssignments?: components["schemas"]["AssignmentNotificationModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    AssignmentDefaultModel: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      /** @example Revestimento dos Banheiros */
      title?: string;
      /**
       * Format: date-time
       * @example 2022-12-28T13:00:33Z
       */
      startDate?: string;
      /**
       * Format: date-time
       * @example 2023-01-20T13:00:33Z
       */
      deadline?: string;
      /**
       * Format: date-time
       * @example 2023-01-20T13:00:33Z
       */
      endDate?: string;
      /** @example true */
      completed?: boolean;
      /** @example false */
      approved?: boolean;
      /**
       * @example OBRAS
       * @enum {string}
       */
      nature?: "LIMPEZA" | "OBRAS";
      workStation?: components["schemas"]["WorkStationModel"];
      _links?: components["schemas"]["Links"];
    };
    PagedModelAssignmentDefaultModel: {
      _embedded?: {
        assignments?: components["schemas"]["AssignmentDefaultModel"][];
      };
      _links?: components["schemas"]["Links"];
      page?: components["schemas"]["PageMetadata"];
    };
    CollectionModelUserDetailedModel: {
      _embedded?: {
        users?: components["schemas"]["UserDetailedModel"][];
      };
      _links?: components["schemas"]["Links"];
    };
    Link: {
      href?: string;
      hreflang?: string;
      title?: string;
      type?: string;
      deprecation?: string;
      profile?: string;
      name?: string;
      templated?: boolean;
    };
  };
  responses: {
    /** @description Requisição inválida */
    BadRequestResponse: {
      content: {
        "application/json": components["schemas"]["Problem"];
      };
    };
    /** @description Recurso não possui representação que poderia ser aceita pelo consumidor */
    NotAcceptableResponse: {
      content: {
        "application/json": components["schemas"]["Problem"];
      };
    };
    /** @description Erro interno no servidor */
    InternalServerErrorResponse: {
      content: {
        "application/json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Deleta uma estação de trabalho */
  findOrFail: {
    parameters: {
      path: {
        /**
         * @description ID de um usuário
         * @example 1
         */
        workStationId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkStationModel"];
        };
      };
      /** @description Estação de Trabalho não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita uma estação de trabalho */
  update: {
    parameters: {
      path: {
        /**
         * @description ID de uma estação de trabalho
         * @example 1
         */
        workStationId: number;
      };
    };
    /** @description Representação de uma estação de trabalho editada */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkStationInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["WorkStationModel"];
        };
      };
      /** @description Setor não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta uma estação de trabalho */
  delete: {
    parameters: {
      path: {
        /**
         * @description ID de uma estação de trabalho
         * @example 1
         */
        workStationId: number;
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      /** @description Estação de Trabalho não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Busca um usuário pelo ID */
  findOrFail_1: {
    parameters: {
      path: {
        /**
         * @description ID de um usuário
         * @example 1
         */
        userId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetailedModel"];
        };
      };
      /** @description Usuário não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita um usuário */
  update_1: {
    parameters: {
      path: {
        /**
         * @description ID de um usuário
         * @example 1
         */
        userId: number;
      };
    };
    /** @description Representação de um usuário editado */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdateInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDetailedModel"];
        };
      };
      /** @description Usuário não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta um usuário */
  delete_1: {
    parameters: {
      path: {
        /**
         * @description ID de um setor
         * @example 1
         */
        userId: number;
      };
    };
    responses: {
      /** @description Colaborador deletado com sucesso */
      204: {
        content: never;
      };
      /** @description ID do colaborador inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Colaborador não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Altera a Senha do usuário */
  changePassword: {
    parameters: {
      path: {
        /**
         * @description ID de um usuário
         * @example 1
         */
        userId: number;
      };
    };
    /** @description Representação de uma nova senha */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordInput"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      /** @description Usuário não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Associa um determinado grupo ao usuário atual */
  associate: {
    parameters: {
      path: {
        userId: number;
        accessGroupId: number;
      };
    };
    responses: {
      /** @description Associação realizada com sucesso */
      204: {
        content: never;
      };
      /** @description ID do usuário/grupo de acesso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Disassocia um determinado grupo ao usuário atual */
  disassociate: {
    parameters: {
      path: {
        userId: number;
        accessGroupId: number;
      };
    };
    responses: {
      /** @description Disassociação realizada com sucesso */
      204: {
        content: never;
      };
      /** @description ID do usuário/grupo de acesso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Usuário não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita um recurso do tipo material */
  updateMaterial: {
    parameters: {
      path: {
        supplyId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplyMaterialInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SupplyDetailedModel"];
        };
      };
      /** @description ID do recurso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita um recurso do tipo equipamento */
  updateEquipment: {
    parameters: {
      path: {
        supplyId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplyEquipmentInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SupplyDetailedModel"];
        };
      };
      /** @description ID do recurso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta um movimento de recurso */
  findById_1: {
    parameters: {
      path: {
        supplyMovementId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SupplyMovementModel"];
        };
      };
      /** @description Movimento de Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita um movimento de recurso */
  update_2: {
    parameters: {
      path: {
        /**
         * @description ID de um movimento de recurso
         * @example 1
         */
        supplyMovementId: number;
      };
    };
    /** @description Representação de um recurso a editar */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplyMovementInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SupplyMovementModel"];
        };
      };
      /** @description Colaborador não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta um movimento de recurso */
  delete_3: {
    parameters: {
      path: {
        supplyMovementId: number;
      };
    };
    responses: {
      /** @description Movimento de recurso deletado com sucesso */
      204: {
        content: never;
      };
      /** @description Movimento de Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Devolve uma quantia de recurso */
  giveBackSupply: {
    parameters: {
      path: {
        /**
         * @description ID de um movimento de recurso
         * @example 1
         */
        supplyMovementId: number;
      };
    };
    /** @description Representação do recurso a devolver */
    requestBody: {
      content: {
        "application/json": components["schemas"]["DevolvedSupplyMovementInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SupplyMovementModel"];
        };
      };
    };
  };
  /** Busca um setor pelo ID */
  findOrFail_2: {
    parameters: {
      path: {
        /**
         * @description ID de um setor
         * @example 1
         */
        sectorId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SectorModel"];
        };
      };
      /** @description ID do setor inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Setor não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita um setor */
  update_3: {
    parameters: {
      path: {
        /**
         * @description ID de um setor
         * @example 1
         */
        sectorId: number;
      };
    };
    /** @description Representação de um setor editado */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SectorInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SectorModel"];
        };
      };
      /** @description ID do setor inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Setor não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta um setor */
  delete_4: {
    parameters: {
      path: {
        /**
         * @description ID de um setor
         * @example 1
         */
        sectorId: number;
      };
    };
    responses: {
      /** @description Setor deletado com sucesso */
      204: {
        content: never;
      };
      /** @description ID do setor inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Setor não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Busca uma taerfa pelo ID */
  findOrFail_3: {
    parameters: {
      path: {
        /** @description ID de iuma tarefa */
        assignmentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AssignmentModel"];
        };
      };
      /** @description Tarefa não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita uma tarefa */
  update_4: {
    parameters: {
      path: {
        /**
         * @description ID de uma tarefa
         * @example 1
         */
        assignmentId: number;
      };
    };
    /** @description Representação de uma tarefa editada */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AssignmentModel"];
        };
      };
      /** @description Tarefa não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta uma tarefa */
  delete_5: {
    parameters: {
      path: {
        assignmentId: number;
      };
    };
    responses: {
      /** @description Tarefa deletada com sucesso */
      204: {
        content: never;
      };
      /** @description Tarefa não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Disassocia um colaborador a determinada tarefa */
  detachEmployee: {
    parameters: {
      path: {
        assignmentId: number;
        employeeResponsibleId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentNotificationInput"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
  /** Associa um colaborador a determinada tarefa */
  attachEmployee: {
    parameters: {
      path: {
        assignmentId: number;
        employeeResponsibleId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentNotificationInput"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
  /** Conclui ou não uma tarefa */
  completeAssignment: {
    parameters: {
      path: {
        /** @description ID de uma tarefa */
        assignmentId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentCompletedInput"];
      };
    };
    responses: {
      /** @description Tarefa completada ou não com sucesso */
      204: {
        content: never;
      };
      /** @description Tarefa não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Aprova ou reprova uma tarefa */
  approveAssignment: {
    parameters: {
      path: {
        /** @description ID de uma tarefa */
        assignmentId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentApprovedInput"];
      };
    };
    responses: {
      /** @description Tarefa aprovada ou reprovada com sucesso */
      204: {
        content: never;
      };
      /** @description Tarefa não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Edita um grupo de acesso */
  update_5: {
    parameters: {
      path: {
        /**
         * @description ID de um grupo de acesso
         * @example 1
         */
        accessGroupId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessGroupInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AccessGroupSummaryModel"];
        };
      };
      /** @description ID do grupo de acesso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Grupo de acesso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta um grupo de acesso */
  delete_6: {
    parameters: {
      path: {
        /**
         * @description ID de um grupo de acesso
         * @example 1
         */
        accessGroupId: number;
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      /** @description ID do grupo de acesso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Grupo de acesso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Associa as permissões relacionadas ao grupo atual */
  associate_1: {
    parameters: {
      path: {
        /** @description ID do grupo de acesso */
        accessGroupId: number;
        /** @description ID da permissão */
        permissionId: number;
      };
    };
    responses: {
      /** @description Associação realizada com sucesso */
      204: {
        content: never;
      };
      /** @description ID do grupo de acesso/permissão inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Grupo de acesso/permissão não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Disassocia as permissões relacionadas ao grupo atual */
  disassociate_1: {
    parameters: {
      path: {
        /** @description ID do grupo de acesso */
        accessGroupId: number;
        /** @description ID da permissão */
        permissionId: number;
      };
    };
    responses: {
      /** @description Disassociação realizada com sucesso */
      204: {
        content: never;
      };
      /** @description ID do grupo de acesso/permissão inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Grupo de acesso/permissão não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Lista as estações de trabalho */
  search: {
    parameters: {
      query?: {
        /**
         * @description Nome da Estação de Trabalho
         * @example Bloco B Apto 178
         */
        workStationName?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelWorkStationModel"];
        };
      };
    };
  };
  /** Cria uma nova estação de trabalho */
  create: {
    /** @description Representação de uma nova estação de trabalho */
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkStationInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["WorkStationModel"];
        };
      };
    };
  };
  /** Lista os usuários */
  search_1: {
    parameters: {
      query?: {
        /**
         * @description Nome do usuário
         * @example Pedro
         */
        userName?: string;
        /**
         * @description Cpf do usuário
         * @example 99999999999
         */
        userCpf?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelUserDetailedModel"];
        };
      };
    };
  };
  /** Cria um novo usuário */
  create_1: {
    /** @description Representação de um novo usuário */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["UserDetailedModel"];
        };
      };
    };
  };
  /** Cria um avatar de usuário */
  upload: {
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["AvatarInput"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AvatarUrlModel"];
        };
      };
    };
  };
  /** Cria um novo recurso do tipo material */
  createMaterial: {
    /** @description Representação de um novo recurso */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplyMaterialInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["SupplyDetailedModel"];
        };
      };
    };
  };
  /** Cria um novo recurso do tipo equipamento */
  createEquipment: {
    /** @description Representação de um novo recurso */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplyEquipmentInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["SupplyDetailedModel"];
        };
      };
    };
  };
  /** Lista os movimentos de recursos */
  all_1: {
    parameters: {
      query?: {
        /** @description Número da página (0..N). */
        page?: number;
        /** @description Quantidade de elementos por página */
        size?: number;
        /** @description Critério de ordenação: propriedade(asc|desc). */
        sort?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelSupplyMovementModel"];
        };
      };
    };
  };
  /** Cria um novo movimento de recurso */
  create_2: {
    /** @description Representação de uma novo movimento de recurso */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupplyMovementInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["SupplyMovementModel"];
        };
      };
      /** @description Estação de Trabalho não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Lista os setores */
  search_3: {
    parameters: {
      query: {
        sectorFilter: components["schemas"]["SectorFilter"];
        /**
         * @description Nome do setor
         * @example Acabamento
         */
        sectorName?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelSectorModel"];
        };
      };
    };
  };
  /** Cria um novo setor */
  create_3: {
    /** @description Representação de um novo setor */
    requestBody: {
      content: {
        "application/json": components["schemas"]["SectorInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["SectorModel"];
        };
      };
    };
  };
  /** Lista as Tarefas */
  search_5: {
    parameters: {
      query?: {
        /**
         * @description Título da Tarefa
         * @example Revestir Banheiros
         */
        assignmentTitle?: string;
        /**
         * @description Data de Início
         * @example 2023-01-10T15:00:00Z
         */
        "A data inicial"?: Record<string, never>;
        /**
         * @description Data de Finalização
         * @example 2023-01-21T14:00:00Z
         */
        endDate?: Record<string, never>;
        /**
         * @description Data final para conclusão
         * @example 2023-01-22T11:07:00Z
         */
        "O prazo para conclusão"?: Record<string, never>;
        /**
         * @description Status de Finalização
         * @example true
         */
        "A conclusão"?: boolean;
        /**
         * @description Status de Aprovação
         * @example false
         */
        "A aprovação"?: boolean;
        /** @description Número da página (0..N). */
        page?: number;
        /** @description Quantidade de elementos por página */
        size?: number;
        /** @description Critério de ordenação: propriedade(asc|desc). */
        sort?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelAssignmentDefaultModel"];
        };
      };
    };
  };
  /** Cria uma nova tarefa */
  create_4: {
    /** @description Representação de um nova tarefa */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignmentInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["AssignmentModel"];
        };
      };
    };
  };
  /** Lista os grupos de acesso */
  all_4: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelAccessGroupSummaryModel"];
        };
      };
    };
  };
  /** Cria um grupo de acesso */
  create_5: {
    /** @description Representação de um a novo grupo de acesso */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccessGroupInput"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          "*/*": components["schemas"]["AccessGroupSummaryModel"];
        };
      };
    };
  };
  /** Lista os grupos de acesso  de cada usuário */
  all: {
    parameters: {
      path: {
        userId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelAccessGroupSummaryModel"];
        };
      };
      /** @description ID do usuário */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Lista os usuários atribuídos ou não a tarefa atual */
  allAssigned: {
    parameters: {
      query?: {
        /**
         * @description Natureza das consulta
         * @example true
         */
        assigned?: boolean;
      };
      path: {
        assignmentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelUserAssignedModel"];
        };
      };
      /** @description ID da tarefa inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Tarefa não encontrada */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Lista recursos */
  search_2: {
    parameters: {
      query?: {
        /**
         * @description Nome do recurso
         * @example Cimento
         */
        supplyName?: string;
        /** @description Número da página (0..N). */
        page?: number;
        /** @description Quantidade de elementos por página */
        size?: number;
        /** @description Critério de ordenação: propriedade(asc|desc). */
        sort?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelSupplySummaryModel"];
        };
      };
    };
  };
  /** Busca um recurso por ID */
  findById: {
    parameters: {
      path: {
        /** @description ID de um recurso */
        supplyId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SupplyDetailedModel"];
        };
      };
      /** @description Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Deleta um recurso */
  delete_2: {
    parameters: {
      path: {
        /** @description ID de um recurso */
        supplyId: number;
      };
    };
    responses: {
      /** @description Recurso deletado com sucesso */
      204: {
        content: never;
      };
      /** @description Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Lista as notificações enviadas, por recursos atribuídos */
  findNotificationBySuppliesAvailable: {
    parameters: {
      query: {
        pageable: components["schemas"]["Pageable"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelSupplyMovementNotificationModel"];
        };
      };
    };
  };
  /** Lista as permissões de cada grupo de acesso */
  all_2: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelPermissionDetailedModel"];
        };
      };
    };
  };
  /** Lista as notificações enviadas por tarefas atribuídas ou não atribuídas */
  findAllAssignedOrUnassigned: {
    parameters: {
      query?: {
        /**
         * @description Atribuição ou não
         * @example assignedTasks
         */
        assign?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelAssignmentNotificationModel"];
        };
      };
    };
  };
  /** Lista as notificações enviadas, completas, aprovadas e por data */
  search_4: {
    parameters: {
      query?: {
        /** @description Estado da tarefa completa (true|false). */
        "A conclusão"?: boolean;
        /** @description Estado da tarefa aprovada (true|false). */
        "A aprovação"?: boolean;
        /**
         * @description Data atual.
         * @example 2023-01-08T22:30:00Z
         */
        currentDate?: Record<string, never>;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedModelAssignmentNotificationModel"];
        };
      };
    };
  };
  /** Lista colaboradores atribuídos a respectivas tarefas */
  all_3: {
    parameters: {
      path: {
        assignmentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelUserDetailedModel"];
        };
      };
    };
  };
  /** Lista as permissões relacionadas ao grupo atual */
  all_5: {
    parameters: {
      path: {
        accessGroupId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CollectionModelPermissionDetailedModel"];
        };
      };
      /** @description ID do grupo de acesso inválido */
      400: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
      /** @description Grupo de acesso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
  /** Disponibiliza um movimento de recurso em estado ocioso */
  vacateSupply: {
    parameters: {
      path: {
        /**
         * @description ID de um movimento de recurso
         * @example 1
         */
        supplyMovementId: number;
      };
    };
    responses: {
      /** @description Recurso desocupado com sucesso */
      204: {
        content: never;
      };
      /** @description Movimento de Recurso não encontrado */
      404: {
        content: {
          "*/*": components["schemas"]["Problem"];
        };
      };
    };
  };
}
